// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwtJKCugENciJSZI6clzmIQnESv9q9M14',
    appId: '1:978505755364:web:042d50cfddc5dd49fadaf1',
    messagingSenderId: '978505755364',
    projectId: 'zima-90160',
    authDomain: 'zima-90160.firebaseapp.com',
    storageBucket: 'zima-90160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM-Xmc-dXbN7TwT7CSRxEzBI7GtiMe0ds',
    appId: '1:978505755364:android:ae524cb7e9bc8b6cfadaf1',
    messagingSenderId: '978505755364',
    projectId: 'zima-90160',
    storageBucket: 'zima-90160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw_ncvFwqvNkr4TYuk3mG5GfIaS8D5oQI',
    appId: '1:978505755364:ios:11c79e1e1fe40edbfadaf1',
    messagingSenderId: '978505755364',
    projectId: 'zima-90160',
    storageBucket: 'zima-90160.appspot.com',
    androidClientId: '978505755364-o4dpnua7soaob5pbei9i9h1er3udjg6m.apps.googleusercontent.com',
    iosClientId: '978505755364-2rj1s5pbmlva1qo8dchk1ubk8t5uvur2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainzima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw_ncvFwqvNkr4TYuk3mG5GfIaS8D5oQI',
    appId: '1:978505755364:ios:0ff877ef33ce6d54fadaf1',
    messagingSenderId: '978505755364',
    projectId: 'zima-90160',
    storageBucket: 'zima-90160.appspot.com',
    androidClientId: '978505755364-o4dpnua7soaob5pbei9i9h1er3udjg6m.apps.googleusercontent.com',
    iosClientId: '978505755364-460njmt4p1vnesjbhgma83k23eqc3u4r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mainzima.RunnerTests',
  );
}
